### ISSUE TITLE
Create Authorization File

### ISSUE THREAD

**Issue by TheresaRutledge** [TheresaRutledge/whats-in-your-fridge#4]
- authMiddleware
- JWT token

**Comment by rhw-git** [comment]
##  1. JWT
- token set up in the Auth.js in the utils folder
- add authentication for ```login, createUser, favoriteRecipe, and deleteRecipe```  in the user-controller.js in the controllers folder
##  2. authMiddleware
- add middleware authentication for User.js in the model folder
- middleware setting is already there in the server.js. no need to update
